[package]
name = "cryptea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
digest = "0.10.7"
hex = "0.4.3"
sha1 = "0.10.5"

anyhow = "1.0"
